### ISSUE TITLE
Getting no references results: "Could not open pipe from crf call"

### ISSUE THREAD

**Issue by jgrossi** [knmnyn/ParsCit#17]
Hi! First thanks for the project!

I'm using ParsCit in my Masters thesis to test some extraction tools and compare results. ParsCit is one of these tools and I've installed it will all dependences, but with no references results. As output I have only an empty `citationList` tag:

`<algorithm name="ParsCit" version="110505">
<citationList>
</citationList>
</algorithm>`

In the first line of output I have this error message: `Fatal Exception: Could not open pipe from crf call: No such file or directory`. Does anyone know how can I fix that?

Thanks for helping.

**Comment by cmkumar87** [comment]
Dear jgrossi

Thanks for usimg ParsCit. It appears that the exception is due to ParsCit to find the CRF++ pacakage. This is a  critical dependency for ParsCit. Please install CRF++ in your machine as we have specified in the install doc foe ParsCit. If you have installed it could you please check if it is in the correct path where ParsCit can find it.
Please also check permissions for directory containing the CRF++ binaries.
Kindly let us know if you were able to resolve your error.
Thanks!
Muthu

**Comment by jgrossi** [comment]
Hi @cmkumar87 ! Thanks for the quick response. I'm gonna check about CRF++. It's installed but maybe the path is wrong and ParsCit is not finding those files. Thanks in advance for the support. Best regards.

**Comment by jgrossi** [comment]
Hi again @cmkumar87! Just for give you a feedback. I've checked my CRF++ install (version 0.58) and everything was ok. It's working as expected, the binaries files pointing to the correct place, but ParsCit configuration file was pointing to a different place.

Now is everything working and CRF++ and ParsCit is extraction all references I need. Thanks for the support. I'm grateful for the help, really. Best regards.

**Comment by cmkumar87** [comment]
Great! Thanks for letting us know!
